In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import os
os.environ["CUDA_DEVICE_ORDER"] = "PCI_BUS_ID"

import sys
module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

In [22]:
import torch
import numpy as np
from tools.loss import *
from scipy.ndimage import distance_transform_edt

In [4]:
def batched_distance_to_nearest_true(masks):
    batch_size = masks.size(0)
    # Prepare a list to store the results for each item in the batch
    distances_batch = []

    for i in range(batch_size):
        # Process each mask in the batch
        mask_np = masks[i].cpu().numpy()
        inverted_mask = np.logical_not(mask_np)
        distances = distance_transform_edt(inverted_mask)
        distances_batch.append(torch.from_numpy(distances))

    # Stack the results to form a batched tensor
    return torch.stack(distances_batch, dim=0)


In [9]:
distance_to_nearest_true(torch.tensor([
    [[0, 1, 0],
    [1, 0, 0],
    [0, 0, 0]],
    [[0, 1, 0],
    [1, 0, 0],
    [0, 0, 0]],
]))

tensor([[[1.0000, 0.0000, 1.0000],
         [0.0000, 1.0000, 1.4142],
         [1.0000, 1.4142, 2.2361]],

        [[1.0000, 0.0000, 1.0000],
         [0.0000, 1.0000, 1.4142],
         [1.0000, 1.4142, 2.2361]]], dtype=torch.float64)

In [19]:
random_tensor = torch.zeros((32, 200, 200))

In [20]:
# random_tensor[:, 80:120, 80:120] = 1

In [21]:
distance_to_nearest_true(random_tensor)

tensor([[[  1.0000,   1.4142,   2.2361,  ..., 197.0025, 198.0025, 199.0025],
         [  1.4142,   1.7321,   2.4495,  ..., 197.0051, 198.0051, 199.0050],
         [  2.2361,   2.4495,   3.0000,  ..., 197.0127, 198.0126, 199.0126],
         ...,
         [197.0025, 197.0051, 197.0127,  ..., 278.6019, 279.3099, 280.0196],
         [198.0025, 198.0051, 198.0126,  ..., 279.3099, 280.0161, 280.7241],
         [199.0025, 199.0050, 199.0126,  ..., 280.0196, 280.7241, 281.4303]],

        [[  2.0000,   2.2361,   2.8284,  ..., 197.0102, 198.0101, 199.0100],
         [  2.2361,   2.4495,   3.0000,  ..., 197.0127, 198.0126, 199.0126],
         [  2.8284,   3.0000,   3.4641,  ..., 197.0203, 198.0202, 199.0201],
         ...,
         [197.0102, 197.0127, 197.0203,  ..., 278.6073, 279.3152, 280.0250],
         [198.0101, 198.0126, 198.0202,  ..., 279.3152, 280.0214, 280.7294],
         [199.0100, 199.0126, 199.0201,  ..., 280.0250, 280.7294, 281.4356]],

        [[  3.0000,   3.1623,   3.6056,  ...

In [29]:
t = torch.tensor([[5, 1, 1]])
l = torch.tensor([[1, 0, 0]])

In [30]:
uce_loss(t, l)

tensor([[1.0000e-10]])